# Generated by Django 4.0.4 on 2022-06-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('numeropag', models.CharField(max_length=10)),
                ('editorial', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=25)),
                ('autor', models.ManyToManyField(to='libros.autor')),
            ],
        ),
    ]
